/*
 * Dayforce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package au.com.camerons.mtdata.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;



/**
 * ProcessResult
 */

public class ProcessResult {
  @SerializedName(value = "Code", alternate = {"code"})
  private String code = null;

  @SerializedName(value = "Context", alternate = {"context"})
  private String context = null;

  @SerializedName(value = "Level", alternate = {"level"})
  private String level = null;

  @SerializedName(value = "Message", alternate = {"message"})
  private String message = null;

  public ProcessResult code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ProcessResult context(String context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public ProcessResult level(String level) {
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  
  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public ProcessResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessResult processResult = (ProcessResult) o;
    return Objects.equals(this.code, processResult.code) &&
        Objects.equals(this.context, processResult.context) &&
        Objects.equals(this.level, processResult.level) &&
        Objects.equals(this.message, processResult.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, context, level, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessResult {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

